# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/crash/Desktop/Projects/Dev/CIVA IRU"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/crash/Desktop/Projects/Dev/CIVA IRU"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" "/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CIVA_IRU

# Build rule for target.
CIVA_IRU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CIVA_IRU
.PHONY : CIVA_IRU

# fast build rule for target.
CIVA_IRU/fast:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/build
.PHONY : CIVA_IRU/fast

datarefs.o: datarefs.cpp.o

.PHONY : datarefs.o

# target to build an object file
datarefs.cpp.o:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o
.PHONY : datarefs.cpp.o

datarefs.i: datarefs.cpp.i

.PHONY : datarefs.i

# target to preprocess a source file
datarefs.cpp.i:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/datarefs.cpp.i
.PHONY : datarefs.cpp.i

datarefs.s: datarefs.cpp.s

.PHONY : datarefs.s

# target to generate assembly for a file
datarefs.cpp.s:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/datarefs.cpp.s
.PHONY : datarefs.cpp.s

functions.o: functions.cpp.o

.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i

.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s

.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/functions.cpp.s
.PHONY : functions.cpp.s

plugin.o: plugin.cpp.o

.PHONY : plugin.o

# target to build an object file
plugin.cpp.o:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/plugin.cpp.o
.PHONY : plugin.cpp.o

plugin.i: plugin.cpp.i

.PHONY : plugin.i

# target to preprocess a source file
plugin.cpp.i:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/plugin.cpp.i
.PHONY : plugin.cpp.i

plugin.s: plugin.cpp.s

.PHONY : plugin.s

# target to generate assembly for a file
plugin.cpp.s:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/plugin.cpp.s
.PHONY : plugin.cpp.s

structs.o: structs.cpp.o

.PHONY : structs.o

# target to build an object file
structs.cpp.o:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/structs.cpp.o
.PHONY : structs.cpp.o

structs.i: structs.cpp.i

.PHONY : structs.i

# target to preprocess a source file
structs.cpp.i:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/structs.cpp.i
.PHONY : structs.cpp.i

structs.s: structs.cpp.s

.PHONY : structs.s

# target to generate assembly for a file
structs.cpp.s:
	$(MAKE) -f CMakeFiles/CIVA_IRU.dir/build.make CMakeFiles/CIVA_IRU.dir/structs.cpp.s
.PHONY : structs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CIVA_IRU"
	@echo "... datarefs.o"
	@echo "... datarefs.i"
	@echo "... datarefs.s"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... plugin.o"
	@echo "... plugin.i"
	@echo "... plugin.s"
	@echo "... structs.o"
	@echo "... structs.i"
	@echo "... structs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

