# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/crash/Desktop/Projects/Dev/CIVA IRU"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/crash/Desktop/Projects/Dev/CIVA IRU"

# Include any dependencies generated for this target.
include CMakeFiles/CIVA_IRU.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/CIVA_IRU.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/CIVA_IRU.dir/flags.make

CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o: CMakeFiles/CIVA_IRU.dir/flags.make
CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o: datarefs.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o -c "/home/crash/Desktop/Projects/Dev/CIVA IRU/datarefs.cpp"

CMakeFiles/CIVA_IRU.dir/datarefs.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/CIVA_IRU.dir/datarefs.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/crash/Desktop/Projects/Dev/CIVA IRU/datarefs.cpp" > CMakeFiles/CIVA_IRU.dir/datarefs.cpp.i

CMakeFiles/CIVA_IRU.dir/datarefs.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/CIVA_IRU.dir/datarefs.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/crash/Desktop/Projects/Dev/CIVA IRU/datarefs.cpp" -o CMakeFiles/CIVA_IRU.dir/datarefs.cpp.s

CMakeFiles/CIVA_IRU.dir/functions.cpp.o: CMakeFiles/CIVA_IRU.dir/flags.make
CMakeFiles/CIVA_IRU.dir/functions.cpp.o: functions.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/CIVA_IRU.dir/functions.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/CIVA_IRU.dir/functions.cpp.o -c "/home/crash/Desktop/Projects/Dev/CIVA IRU/functions.cpp"

CMakeFiles/CIVA_IRU.dir/functions.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/CIVA_IRU.dir/functions.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/crash/Desktop/Projects/Dev/CIVA IRU/functions.cpp" > CMakeFiles/CIVA_IRU.dir/functions.cpp.i

CMakeFiles/CIVA_IRU.dir/functions.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/CIVA_IRU.dir/functions.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/crash/Desktop/Projects/Dev/CIVA IRU/functions.cpp" -o CMakeFiles/CIVA_IRU.dir/functions.cpp.s

CMakeFiles/CIVA_IRU.dir/plugin.cpp.o: CMakeFiles/CIVA_IRU.dir/flags.make
CMakeFiles/CIVA_IRU.dir/plugin.cpp.o: plugin.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/CIVA_IRU.dir/plugin.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/CIVA_IRU.dir/plugin.cpp.o -c "/home/crash/Desktop/Projects/Dev/CIVA IRU/plugin.cpp"

CMakeFiles/CIVA_IRU.dir/plugin.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/CIVA_IRU.dir/plugin.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/crash/Desktop/Projects/Dev/CIVA IRU/plugin.cpp" > CMakeFiles/CIVA_IRU.dir/plugin.cpp.i

CMakeFiles/CIVA_IRU.dir/plugin.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/CIVA_IRU.dir/plugin.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/crash/Desktop/Projects/Dev/CIVA IRU/plugin.cpp" -o CMakeFiles/CIVA_IRU.dir/plugin.cpp.s

CMakeFiles/CIVA_IRU.dir/structs.cpp.o: CMakeFiles/CIVA_IRU.dir/flags.make
CMakeFiles/CIVA_IRU.dir/structs.cpp.o: structs.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/CIVA_IRU.dir/structs.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/CIVA_IRU.dir/structs.cpp.o -c "/home/crash/Desktop/Projects/Dev/CIVA IRU/structs.cpp"

CMakeFiles/CIVA_IRU.dir/structs.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/CIVA_IRU.dir/structs.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/crash/Desktop/Projects/Dev/CIVA IRU/structs.cpp" > CMakeFiles/CIVA_IRU.dir/structs.cpp.i

CMakeFiles/CIVA_IRU.dir/structs.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/CIVA_IRU.dir/structs.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/crash/Desktop/Projects/Dev/CIVA IRU/structs.cpp" -o CMakeFiles/CIVA_IRU.dir/structs.cpp.s

# Object files for target CIVA_IRU
CIVA_IRU_OBJECTS = \
"CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o" \
"CMakeFiles/CIVA_IRU.dir/functions.cpp.o" \
"CMakeFiles/CIVA_IRU.dir/plugin.cpp.o" \
"CMakeFiles/CIVA_IRU.dir/structs.cpp.o"

# External object files for target CIVA_IRU
CIVA_IRU_EXTERNAL_OBJECTS =

output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/datarefs.cpp.o
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/functions.cpp.o
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/plugin.cpp.o
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/structs.cpp.o
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/build.make
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libGLEWmx.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libacfutils.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libcairo.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libcharset.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libcrypto.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libcurl.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libfreetype.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libiconv.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/liblzma.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libogg.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libopus.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libopusfile.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libopusurl.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libpcre2-8.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libpixman-1.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libpng16.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libproj.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libshp.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libssl.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libxml2.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: libacfutils/lin64/lib/libz.a
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: /usr/local/lib/libGeographic.so.19.2.0
output/CIVA_IRU/lin_x64/CIVA_IRU.xpl: CMakeFiles/CIVA_IRU.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Linking CXX shared library output/CIVA_IRU/lin_x64/CIVA_IRU.xpl"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/CIVA_IRU.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/CIVA_IRU.dir/build: output/CIVA_IRU/lin_x64/CIVA_IRU.xpl

.PHONY : CMakeFiles/CIVA_IRU.dir/build

CMakeFiles/CIVA_IRU.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/CIVA_IRU.dir/cmake_clean.cmake
.PHONY : CMakeFiles/CIVA_IRU.dir/clean

CMakeFiles/CIVA_IRU.dir/depend:
	cd "/home/crash/Desktop/Projects/Dev/CIVA IRU" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/crash/Desktop/Projects/Dev/CIVA IRU" "/home/crash/Desktop/Projects/Dev/CIVA IRU" "/home/crash/Desktop/Projects/Dev/CIVA IRU" "/home/crash/Desktop/Projects/Dev/CIVA IRU" "/home/crash/Desktop/Projects/Dev/CIVA IRU/CMakeFiles/CIVA_IRU.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/CIVA_IRU.dir/depend

