# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
CXX_FLAGS =  --std=c++14 -g -fPIC  

CXX_DEFINES = -DAPL=0 -DCIVA_IRU_EXPORTS -DDEBUG -DIBM=0 -DLIN=1 -DXPLM200=1 -DXPLM210=1 -DXPLM300=1 -DXPLM301=1

CXX_INCLUDES = -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/CIVA_IRU" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/PUBLIC" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/XPLSDK303/CHeaders/XPLM" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/XPLSDK303/CHeaders/Widgets" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/XPLSDK303/CHeaders/Wrappers" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/libacfutils/include" -I"/home/crash/Desktop/Projects/Dev/CIVA IRU/libacfutils/lin64/include" -I/usr/local/include/GeographicLib 

